# Generated by Django 5.2.17 on 2026-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_pathway_progress', '0005_auto_20221007_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallearnerpathwayprogress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical learner pathway progress', 'verbose_name_plural': 'historical learner pathway progresss'},
        ),
        migrations.AlterField(
            model_name='historicallearnerpathwayprogress',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
